### ISSUE TITLE
Multiple Bot instances, user and shortlink

### ISSUE THREAD

**Issue by Gareryer** [Sachinanand99/File-Sharing-Telegram-bot#11]
is it possible that a particular deployment can have multiple bots attached to it? That is, one file link that is generated can take user to any available of bot that is free.

Just like we can have multiple admins, can we have multiple bots like tg1bot, tg2bot, tg3bot, tg(x)bot attached to one deployment incase a tg1bot get reported and unavailable but the same link can still take users to another available bot.

Whhen a new user interact with the bot with /start this happens
`[16-Jul-24 21:37:09 - ERROR] - pyrogram.dispatcher - 'Bot' object has no attribute 'invitelink2'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 440, in handler_worker
    await handler.callback(self.client, *args)
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/usr/local/lib/python3.10/dist-packages/pyromod/listen/listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "/usr/local/bin/fileshare/plugins/start.py", line 188, in not_joined
    url=client.invitelink2),
AttributeError: 'Bot' object has no attribute 'invitelink2'. Did you mean: 'invitelink'?`
They cannot use the bot to get links until they /auth first, why require the Owner to approve them as admin instead of user. and what's the essence of /add_prem

Shortlink is not working after adding api key as well.

**Comment by Sachinanand99** [comment]
it is not possible to attach multiple bots once. you can dm me in tg regarding second issue

**Comment by Gareryer** [comment]
> it is not possible to attach multiple bots once. you can dm me in tg regarding second issue

There's a MultiClient feature on this particular [Bot ](https://github.com/SpringsFern/FileStreamBot) for reference.
your Telegram

**Comment by Sachinanand99** [comment]
@Gareryer i don't found any source written in that repo for multiclient feature. Its only written in readme.md
