### ISSUE TITLE
deploye

### ISSUE THREAD

**Issue by mayurgavhane03** [Sachinanand99/File-Sharing-Telegram-bot#12]
i dont have credit card so i am not able to deploy it to so is there any platform to deploy the bot without credit card

**Comment by Sachinanand99** [comment]
@mayurgavhane03 you can deploy it on koyeb and render

**Comment by mayurgavhane03** [comment]
they also require credit and debit card

**Comment by Sachinanand99** [comment]
@mayurgavhane03 use as web service instead of worker on koyeb. it will work
