### ISSUE TITLE
file deletion time 

### ISSUE THREAD

**Issue by mayurgavhane03** [Sachinanand99/File-Sharing-Telegram-bot#13]
What if i want to disable deltion time or i dont want that feature first i put 0 file get delete instantly - i put this it giving error

**Comment by Sachinanand99** [comment]
Non deletion is not implemented on my project. If you want, I can add that too.

**Comment by mayurgavhane03** [comment]
plz add it will be very helpful

**Comment by Sachinanand99** [comment]
added
