### ISSUE TITLE
i am not able to resolve this error i also not understand if u have time try guid me 

### ISSUE THREAD

**Issue by mayurgavhane03** [Sachinanand99/File-Sharing-Telegram-bot#14]
File "/home/ubuntu/course-hub-bot/venv/lib/python3.12/site-packages/pyromod/listen/message_handler.py", line 58, in check
0|my-pytho |     await self.check_if_has_matching_listener(client, message)
0|my-pytho |   File "/home/ubuntu/course-hub-bot/venv/lib/python3.12/site-packages/pyromod/listen/message_handler.py", line 37, in check_if_has_matching_listener
0|my-pytho |     listener = client.get_listener_matching_with_data(data, ListenerTypes.MESSAGE)
0|my-pytho |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0|my-pytho |   File "/home/ubuntu/course-hub-bot/venv/lib/python3.12/site-packages/pyrogram/sync.py", line 54, in async_to_sync_wrap
0|my-pytho |     coroutine = function(*args, **kwargs)
0|my-pytho |                 ^^^^^^^^^^^^^^^^^^^^^^^^^
0|my-pytho |   File "/home/ubuntu/course-hub-bot/venv/lib/python3.12/site-packages/pyromod/listen/client.py", line 123, in get_listener_matching_with_data
0|my-pytho |     for listener in self.listeners[listener_type]:
0|my-pytho |                     ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
0|my-pytho | KeyError: <ListenerTypes.MESSAGE: 'message'>

**Comment by Sachinanand99** [comment]
Try updating packages and using latest commit
